### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by davittomasso** [jeremy-coleman/cogdev-electron#1]
http://joxi.ru/Vrwyxa3tKjxaW2

**Comment by davittomasso** [comment]
Linux 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jeremy-coleman** [comment]
rip that repo
